import SiteText from "./SiteText";
import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api";
import EditorModal from "./EditorModal";

const models = {
  events: { label: "Events", fields: ["title","description","location","starts_at","status"] },
  posts: { label: "Posts", fields: ["title","body","category","image_url","featured","status"] },
  rewards: { label: "Rewards", fields: ["name","description","image_url","sponsor_name","points_cost","inventory","status"] },
  companies: { label: "Companies", fields: ["name","category","image_url","website","status","spotlight_position"] },
  users: { label: "Users", fields: ["first_name","last_name","email","role","status"] },
  employees: { label: "Employees", fields: ["user_id","company_id","title","status"] },
};
const editorFields = model => model === "events" ? ["title","description","category","image_url","location","starts_at","ends_at","capacity","attendance_code","points_awarded"] : models[model].fields;
const statusOptions = ["pending","approved","denied"];

function AdminCMS({ user }) {
  const [active, setActive] = useState("events"); const [items, setItems] = useState([]);
  const [summary, setSummary] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [creating, setCreating] = useState(false); const [form, setForm] = useState({});
  const [editingId,setEditingId]=useState(null); const [saving,setSaving]=useState(false);
  const closeEditor=()=>{setCreating(false);setEditingId(null);setForm({});setError("");};
  const editItem=item=>{const fields=Object.fromEntries(editorFields(active).map(field=>[field,item[field]??""]));for(const field of ["starts_at","ends_at"]){if(fields[field]){const date=new Date(fields[field]);fields[field]=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}}setForm(fields);setEditingId(item.id);setError("");};
  const isAdmin = user && ["admin","board"].includes(user.role);
  const load = useCallback(async () => {
    if (!isAdmin) return; setLoading(true); setError("");
    try { const [records, dashboard] = await Promise.all([api(`/${active}`), api("/dashboard/summary")]); setItems(records); setSummary(dashboard); }
    catch (err) { setError(err.message); } finally { setLoading(false); }
  }, [active,isAdmin]);
  useEffect(() => { const request = window.setTimeout(load, 0); return () => window.clearTimeout(request); }, [load]);
  if (!isAdmin) return <section className="cmsGate"><h2><SiteText contentKey="AdminCMS.e703a2005585">{"Board & Admin workspace"}</SiteText></h2><p><SiteText contentKey="AdminCMS.26198f0fac9e">{"Sign in with an authorized board or administrator account to manage community content, approvals, and activity."}</SiteText></p></section>;

  const update = async (id, changes) => { try { await api(`/${active}/${id}`, {method:"PATCH",body:JSON.stringify(changes)}); await load(); } catch(err) { setError(err.message); } };
  const remove = async (id) => { if (!window.confirm(`Delete this ${active.slice(0,-1)}?`)) return; try { await api(`/${active}/${id}`,{method:"DELETE"}); await load(); } catch(err) { setError(err.message); } };
  const create = async (event) => {
    event.preventDefault(); setSaving(true); setError(""); const payload={...form};
    if(active==="events"){for(const field of ["starts_at","ends_at"]) if(field in payload) payload[field]=payload[field]?new Date(payload[field]).toISOString():null;if("capacity" in payload) payload.capacity=payload.capacity?Number(payload.capacity):null;}
    if (!editingId) {if (active === "events") payload.creator_id=user.id; if (active === "posts") payload.author_id=user.id; if (active === "companies") payload.owner_id=user.id;}
    try { await api(editingId?`/${active}/${editingId}`:`/${active}`,{method:editingId?"PATCH":"POST",body:JSON.stringify(payload)}); closeEditor(); await load(); } catch(err) { setError(err.message); } finally {setSaving(false);}
  };
  const displayFields=models[active].fields;
  return <section className="cmsShell">
    <div className="cmsHeader"><div><p className="eyebrow"><SiteText contentKey="AdminCMS.94f13f58b991">{"Content management"}</SiteText></p><h2><SiteText contentKey="AdminCMS.6bd29e444c2f">{"Community operations"}</SiteText></h2></div>{active!=="posts"||user.role==="admin"?<button className="primaryButton" onClick={() => {setForm(active==="rewards"?{points_cost:0}:{});setEditingId(null);setError("");setCreating(true);}}><SiteText contentKey="AdminCMS.3037552ce1f4">{"+ Add "}</SiteText>{models[active].label.slice(0,-1)}</button>:null}</div>
    {summary && <div className="summaryGrid"><div><strong>{summary.counts.users}</strong><span><SiteText contentKey="AdminCMS.1044a4c056d0">{"Members"}</SiteText></span></div><div><strong>{summary.counts.events}</strong><span><SiteText contentKey="AdminCMS.8d14f6e72de8">{"Events"}</SiteText></span></div><div><strong>{summary.counts.rewards}</strong><span><SiteText contentKey="AdminCMS.59afe47d9d37">{"Rewards"}</SiteText></span></div><div><strong>{summary.counts.redemptions}</strong><span><SiteText contentKey="AdminCMS.7d049a2651c5">{"Rewards redeemed"}</SiteText></span></div><div><strong>{Object.values(summary.pending).reduce((a,b)=>a+b,0)}</strong><span><SiteText contentKey="AdminCMS.ae25c9b1d366">{"Awaiting approval"}</SiteText></span></div></div>}
    <div className="cmsTabs" role="tablist">{Object.entries(models).map(([key,value])=><button key={key} className={active===key?"active":""} onClick={()=>{setActive(key);closeEditor();}}><SiteText section="AdminCMS">{value.label}</SiteText><span>{summary?.counts[key] ?? 0}</span></button>)}</div>
    {(creating||editingId) && <EditorModal title={`${editingId?"Edit":"Create"} ${models[active].label.slice(0,-1)}`} busy={saving} onClose={closeEditor}><form className="createPanel" onSubmit={create}><h3><SiteText section="AdminCMS">{editingId?"Update details":"Add details"}</SiteText></h3><div className="createGrid">{editorFields(active).filter(f=>!['status','role'].includes(f)).map(field=><label key={field}><SiteText section="AdminCMS">{field==='points_cost'?'Point cost (0 = free)':field.replaceAll('_',' ')}</SiteText>{['description','body'].includes(field)?<textarea required value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})}/>:field==='image_url'&&['rewards','posts','events'].includes(active)?<><input type="url" placeholder="https://example.com/image.jpg" value={String(form.image_url||'').startsWith('data:')?'':form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value.trim()})}/><span className="uploadButton"><SiteText section="AdminCMS">{form.image_url?"Image selected":`Or upload ${active==='rewards'?'reward':active==='events'?'event':'post'} image`}</SiteText><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setError('Image must be smaller than 2 MB.');return;}const reader=new FileReader();reader.onload=()=>setForm({...form,image_url:reader.result});reader.readAsDataURL(file);}}/></span></>:<input required={!['website','image_url','company_id','inventory','spotlight_position','featured','ends_at','capacity','attendance_code'].includes(field)} min={field.includes('points')||field==='featured'?0:field==='inventory'||field==='capacity'?1:undefined} step={field.includes('points')?1:undefined} type={['starts_at','ends_at'].includes(field)?'datetime-local':field.includes('id')||field.includes('points')||field==='inventory'||field==='capacity'||field==='spotlight_position'||field==='featured'?'number':'text'} value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})}/>}</label>)}</div><div className="formActions"><button type="button" className="secondaryButton" disabled={saving} onClick={closeEditor}><SiteText contentKey="AdminCMS.19766ed6ccb2">{"Cancel"}</SiteText></button><button className="primaryButton" disabled={saving}><SiteText section="AdminCMS">{saving?"Saving…":editingId?"Save changes":"Save"}</SiteText></button></div>{error&&<p className="formMessage" role="alert">{error}</p>}</form></EditorModal>}
    {error && <p className="formMessage">{error}</p>}
    <div className="cmsTableWrap"><table className="cmsTable"><thead><tr>{displayFields.map(field=><th key={field}>{field.replaceAll('_',' ')}</th>)}<th><SiteText contentKey="AdminCMS.ff8059dc6752">{"Actions"}</SiteText></th></tr></thead><tbody>{loading?<tr><td colSpan={displayFields.length+1}><SiteText contentKey="AdminCMS.ba3bbbe10d8b">{"Loading…"}</SiteText></td></tr>:items.length===0?<tr><td colSpan={displayFields.length+1}><SiteText contentKey="AdminCMS.05f8bb36f881">{"No "}</SiteText>{active}<SiteText contentKey="AdminCMS.3137370298d2">{" yet."}</SiteText></td></tr>:items.map(item=><tr key={item.id}>{displayFields.map(field=><td key={field}>{field==='status'?<select value={item[field]} onChange={e=>update(item.id,{status:e.target.value})}>{[...new Set([item[field],...statusOptions,'active','suspended'])].map(v=><option key={v}>{v}</option>)}</select>:field==='role'?<select value={item.role} onChange={e=>update(item.id,{role:e.target.value})}>{['member','employee','board','admin'].map(v=><option key={v}>{v}</option>)}</select>:field==='spotlight_position'?<select value={item.spotlight_position||''} disabled={item.status!=="approved"} onChange={e=>update(item.id,{spotlight_position:e.target.value?Number(e.target.value):null})}><option value=""><SiteText contentKey="AdminCMS.7ea94b5435c5">{"Not spotlighted"}</SiteText></option>{[1,2,3,4,5].map(slot=><option value={slot} key={slot}><SiteText contentKey="AdminCMS.807870103aec">{"Slot "}</SiteText>{slot}</option>)}</select>:field==='image_url'?<label className="cmsImageUpload"><span style={{backgroundImage:`url(${item.image_url||'/images/impDirectory.png'})`}}></span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setError(`${active==='rewards'?'Reward':'Business'} image must be smaller than 2 MB.`);return;}const reader=new FileReader();reader.onload=()=>update(item.id,{image_url:reader.result});reader.readAsDataURL(file);}}/></label>:<span title={item[field]}>{String(item[field]??'—')}</span>}</td>)}<td><button className="tableButton" onClick={()=>editItem(item)}><SiteText contentKey="AdminCMS.464c4ffd019e">{"Edit"}</SiteText></button><button className="tableButton danger" onClick={()=>remove(item.id)}><SiteText contentKey="AdminCMS.e2d0a54968ea">{"Delete"}</SiteText></button></td></tr>)}</tbody></table></div>
    {summary?.activity?.length>0 && <div className="activityPanel"><h3><SiteText contentKey="AdminCMS.6cb44b56336a">{"Recent activity"}</SiteText></h3>{summary.activity.map(entry=><p key={entry.id}><strong><SiteText section="AdminCMS">{entry.first_name ? `${entry.first_name} ${entry.last_name}` : 'System'}</SiteText></strong> {entry.action} {entry.entity_type} #{entry.entity_id}</p>)}</div>}
  </section>;
}
export default AdminCMS;
