import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";

const categories=["All","Community","Health","Finances","Entertainment","Business","Youth","Local News"];
const emptyPost={title:"",body:"",category:"Community",image_url:""};

function CommunityFeed({ user, onProfileClick }) {
  const [posts,setPosts]=useState([]);const [category,setCategory]=useState("All");const [loading,setLoading]=useState(true);const [openComments,setOpenComments]=useState(null);const [comments,setComments]=useState({});const [notice,setNotice]=useState("");const [composing,setComposing]=useState(false);const [postForm,setPostForm]=useState(emptyPost);const [publishing,setPublishing]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setPosts(await api("/community-posts"));}catch(error){setNotice(error.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const request=window.setTimeout(load,0);return()=>window.clearTimeout(request);},[load,user]);
  const visible=useMemo(()=>category==="All"?posts:posts.filter(post=>post.category===category),[posts,category]);
  const requireUser=()=>{if(user)return true;onProfileClick();return false;};
  const action=async(post,type,payload={})=>{if(!requireUser())return;setNotice("");try{const result=await api(`/posts/${post.id}/${type}`,{method:"POST",body:JSON.stringify(payload)});if(type==="share"){if(navigator.share){try{await navigator.share({title:post.title,text:post.body,url:window.location.href});}catch{/* sharing was cancelled */}}else if(navigator.clipboard){await navigator.clipboard.writeText(window.location.href);setNotice("Feed link copied to your clipboard.");}}else if(result.message)setNotice(result.message);await load();}catch(error){setNotice(error.message);}};
  const submitComment=async(event,post)=>{event.preventDefault();const body=comments[post.id]?.trim();if(!body)return;await action(post,"comment",{body});setComments(current=>({...current,[post.id]:""}));};
  const selectPostImage=event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setNotice("Post image must be smaller than 2 MB.");return;}const reader=new FileReader();reader.onload=()=>setPostForm(current=>({...current,image_url:reader.result}));reader.readAsDataURL(file);};
  const publish=async event=>{event.preventDefault();setPublishing(true);try{await api("/posts",{method:"POST",body:JSON.stringify(postForm)});setPostForm(emptyPost);setComposing(false);setNotice("Your community post is now live.");await load();}catch(error){setNotice(error.message);}finally{setPublishing(false);}};
  const formatDate=value=>new Date(value).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});

  return <section className="communityFeed" aria-labelledby="community-feed-heading">
    <header className="feedHero"><div><p>Impact Arlington Community Hub</p><h2 id="community-feed-heading">Good news travels <em>together.</em></h2><span>Stories, resources, and local moments curated by the Impact Arlington team.</span></div><aside><strong>{posts.length}</strong><small>community stories</small></aside></header>
    <div className="feedControls"><nav aria-label="Post categories">{categories.map(item=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</nav>{user?.role==="admin"&&<button className="feedComposeButton" onClick={()=>setComposing(!composing)}>＋ Create post</button>}</div>
    {composing&&<form className="feedComposer" onSubmit={publish}><div><p>Admin publishing desk</p><h3>Share something meaningful</h3></div><div className="feedComposerGrid"><label>Post title<input required value={postForm.title} onChange={event=>setPostForm({...postForm,title:event.target.value})}/></label><label>Category<select value={postForm.category} onChange={event=>setPostForm({...postForm,category:event.target.value})}>{categories.slice(1).map(item=><option key={item}>{item}</option>)}</select></label><label className="feedComposerWide">Post message<textarea required maxLength="3000" value={postForm.body} onChange={event=>setPostForm({...postForm,body:event.target.value})}/></label><label className="feedImageUpload">Cover image<span style={postForm.image_url?{backgroundImage:`url(${postForm.image_url})`}:undefined}>{postForm.image_url?"Image selected":"Choose a JPG, PNG, or WebP image"}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={selectPostImage}/></label></div><div className="formActions"><button type="button" className="secondaryButton" onClick={()=>setComposing(false)}>Cancel</button><button className="primaryButton" disabled={publishing}>{publishing?"Publishing…":"Publish post"}</button></div></form>}
    {notice&&<p className="feedNotice" role="status">{notice}</p>}
    <div className="feedScrollRegion">
      <aside className="feedRail"><p>Now viewing</p><strong>{category}</strong><span>{visible.length} {visible.length===1?"story":"stories"}</span><div></div><small>Scroll to explore<br/>the entire feed</small></aside>
      <div className="feedStream">{loading?<p className="feedLoading">Gathering community stories…</p>:visible.map((post,index)=><article className={`feedPost${post.featured?" featured":""}`} key={post.id} style={{"--post-depth":`${index%3}`}}>
        <div className="feedPostImage" style={{backgroundImage:`linear-gradient(180deg,rgba(9,34,47,.04),rgba(9,34,47,.72)),url(${post.image_url||'/images/banner.png'})`}}><span>{post.category}</span>{post.featured&&<b>Editor’s pick</b>}<div><small>{formatDate(post.created_at)}</small><strong>{post.title}</strong></div></div>
        <div className="feedPostBody"><div className="feedAuthor"><span>{post.avatar_url?<img src={post.avatar_url} alt=""/>:<>{post.first_name[0]}{post.last_name[0]}</>}</span><p><strong>{post.first_name} {post.last_name}</strong><small>Impact Arlington editorial team</small></p></div><p className="feedCopy">{post.body}</p><div className="feedStats"><span>{post.like_count} likes</span><span>{post.comments.length} comments</span><span>{post.share_count} shares</span></div><div className="feedActions"><button className={post.liked?"active":""} onClick={()=>action(post,"like")}>{post.liked?"♥ Liked":"♡ Like"}</button><button onClick={()=>setOpenComments(openComments===post.id?null:post.id)}>◯ Comment</button><button onClick={()=>action(post,"share")}>↗ Share</button></div>
        {openComments===post.id&&<div className="feedComments">{post.comments.map(comment=><div key={comment.id}><span>{comment.avatar_url?<img src={comment.avatar_url} alt=""/>:<>{comment.first_name[0]}{comment.last_name[0]}</>}</span><p><strong>{comment.first_name} {comment.last_name}</strong>{comment.body}</p></div>)}{!post.comments.length&&<p className="feedEmptyComments">Start a positive conversation.</p>}<form onSubmit={event=>submitComment(event,post)}><input required maxLength="500" placeholder={user?"Write a comment…":"Sign in to comment"} value={comments[post.id]||""} onChange={event=>setComments({...comments,[post.id]:event.target.value})}/><button>Post</button></form></div>}
        </div>
      </article>)}{!loading&&!visible.length&&<div className="feedEmpty"><span>◇</span><h3>No posts in this category yet</h3><p>The Impact Arlington team will publish something here soon.</p></div>}</div>
    </div>
  </section>;
}

export default CommunityFeed;
