import SiteText from "./SiteText";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api } from "../lib/api";
import LinkedText from "./LinkedText";
import EditorModal from "./EditorModal";
import ImageLightbox from "./ImageLightbox";

const categories=["All","Community","Health","Finances","Entertainment","Business","Youth","Local News"];
const emptyPost={title:"",body:"",category:"Community",image_url:""};

function CommunityFeed({ user, onProfileClick }) {
  const [posts,setPosts]=useState([]);const [category,setCategory]=useState("All");const [loading,setLoading]=useState(true);const [openComments,setOpenComments]=useState(null);const [comments,setComments]=useState({});const [notice,setNotice]=useState("");const [composing,setComposing]=useState(false);const [postForm,setPostForm]=useState(emptyPost);const [publishing,setPublishing]=useState(false);
  const [editingId,setEditingId]=useState(null);
  const [enlargedPost,setEnlargedPost]=useState(null);
  const composerRef=useRef(null);
  useEffect(()=>{if(composing){composerRef.current?.querySelector("input")?.focus();}},[composing,editingId]);
  const editPost=post=>{setEditingId(post.id);setPostForm({title:post.title,body:post.body,category:post.category,image_url:post.image_url||""});setNotice("");setComposing(true);};
  const load=useCallback(async()=>{setLoading(true);try{setPosts(await api("/community-posts"));}catch(error){setNotice(error.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const request=window.setTimeout(load,0);return()=>window.clearTimeout(request);},[load,user]);
  const visible=useMemo(()=>category==="All"?posts:posts.filter(post=>post.category===category),[posts,category]);
  const requireUser=()=>{if(user)return true;onProfileClick();return false;};
  const action=async(post,type,payload={})=>{if(!requireUser())return;setNotice("");try{const result=await api(`/posts/${post.id}/${type}`,{method:"POST",body:JSON.stringify(payload)});if(type==="share"){if(navigator.share){try{await navigator.share({title:post.title,text:post.body,url:window.location.href});}catch{/* sharing was cancelled */}}else if(navigator.clipboard){await navigator.clipboard.writeText(window.location.href);setNotice("Feed link copied to your clipboard.");}}else if(result.message)setNotice(result.message);await load();}catch(error){setNotice(error.message);}};
  const submitComment=async(event,post)=>{event.preventDefault();const body=comments[post.id]?.trim();if(!body)return;await action(post,"comment",{body});setComments(current=>({...current,[post.id]:""}));};
  const selectPostImage=event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024){setNotice("Post image must be smaller than 2 MB.");return;}const reader=new FileReader();reader.onload=()=>setPostForm(current=>({...current,image_url:reader.result}));reader.readAsDataURL(file);};
  const publish=async event=>{event.preventDefault();setPublishing(true);try{await api(editingId?`/posts/${editingId}`:"/posts",{method:editingId?"PATCH":"POST",body:JSON.stringify(postForm)});setPostForm(emptyPost);setComposing(false);setNotice(editingId?"Your post has been updated.":"Your community post is now live.");setEditingId(null);setCategory(postForm.category);await load();}catch(error){setNotice(error.message);}finally{setPublishing(false);}};
  const formatDate=value=>new Date(value).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});

  return <section className="communityFeed" aria-labelledby="community-feed-heading">
    <header className="feedHero"><div><p><SiteText contentKey="CommunityFeed.3a8a26379ba3">{"Impact Arlington Community Hub"}</SiteText></p><h2 id="community-feed-heading"><SiteText contentKey="CommunityFeed.4f8affc2bbc9">{"Good news travels "}</SiteText><em><SiteText contentKey="CommunityFeed.25e3d2254208">{"together."}</SiteText></em></h2><span><SiteText contentKey="CommunityFeed.3788b119e4ff">{"Stories, resources, and local moments curated by the Impact Arlington team."}</SiteText></span></div><aside><strong>{posts.length}</strong><small><SiteText contentKey="CommunityFeed.7d2369e6897c">{"community stories"}</SiteText></small></aside></header>
    <div className="feedControls"><nav aria-label="Post categories">{categories.map(item=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</nav>{user?.role==="admin"&&<button className="feedComposeButton" disabled={publishing} onClick={()=>{setEditingId(null);setPostForm(emptyPost);setComposing(true);setNotice("");}}><SiteText contentKey="CommunityFeed.7b743cdfe897">{"＋ Create post"}</SiteText></button>}</div>
    {composing&&user?.role==="admin"&&<EditorModal title={editingId?"Edit community post":"Create community post"} busy={publishing} onClose={()=>{setComposing(false);setEditingId(null);setPostForm(emptyPost);}}><form ref={composerRef} className="feedComposer" onSubmit={publish}><div><p><SiteText contentKey="CommunityFeed.31951e8ba27c">{"Admin publishing desk"}</SiteText></p><h3><SiteText section="CommunityFeed">{editingId?"Edit community post":"Share something meaningful"}</SiteText></h3></div><div className="feedComposerGrid"><label><SiteText contentKey="CommunityFeed.c45dcb7f09b3">{"Post title"}</SiteText><input required value={postForm.title} onChange={event=>setPostForm({...postForm,title:event.target.value})}/></label><label><SiteText contentKey="CommunityFeed.292c06f0045a">{"Category"}</SiteText><select value={postForm.category} onChange={event=>setPostForm({...postForm,category:event.target.value})}>{categories.slice(1).map(item=><option key={item}>{item}</option>)}</select></label><label className="feedComposerWide"><SiteText contentKey="CommunityFeed.f5290c633c5c">{"Post message"}</SiteText><textarea required maxLength="3000" value={postForm.body} onChange={event=>setPostForm({...postForm,body:event.target.value})}/></label><p className="feedComposerWide fieldHint"><SiteText contentKey="CommunityFeed.77dc3829a773">{"Paste website links into your message; they become clickable when published."}</SiteText></p><label className="feedComposerWide"><SiteText contentKey="CommunityFeed.6aeec91b65e7">{"Cover image URL"}</SiteText><input type="url" placeholder="https://example.com/image.jpg" value={postForm.image_url.startsWith("data:")?"":postForm.image_url} onChange={event=>setPostForm({...postForm,image_url:event.target.value.trim()})}/></label><label className="feedImageUpload"><SiteText contentKey="CommunityFeed.d160571e995f">{"Or upload a cover image"}</SiteText><span style={postForm.image_url?{backgroundImage:`url(${postForm.image_url})`}:undefined}><SiteText section="CommunityFeed">{postForm.image_url?"Image selected":"Choose a JPG, PNG, or WebP image"}</SiteText></span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={selectPostImage}/></label></div><div className="formActions"><button type="button" className="secondaryButton" disabled={publishing} onClick={()=>{setComposing(false);setEditingId(null);setPostForm(emptyPost);}}><SiteText contentKey="CommunityFeed.19766ed6ccb2">{"Cancel"}</SiteText></button><button className="primaryButton" disabled={publishing}><SiteText section="CommunityFeed">{publishing?(editingId?"Saving…":"Publishing…"):(editingId?"Save changes":"Publish post")}</SiteText></button></div>{notice&&<p className="formMessage" role="alert">{notice}</p>}</form></EditorModal>}
    {notice&&<p className="feedNotice" role="status">{notice}</p>}
    <div className="feedScrollRegion">
      <aside className="feedRail"><p><SiteText contentKey="CommunityFeed.4946c8a078f2">{"Now viewing"}</SiteText></p><strong>{category}</strong><span>{visible.length} <SiteText section="CommunityFeed">{visible.length===1?"story":"stories"}</SiteText></span><div></div><small><SiteText contentKey="CommunityFeed.fc0c791c8278">{"Scroll to explore"}</SiteText><br/><SiteText contentKey="CommunityFeed.a2cca005a9d5">{"the entire feed"}</SiteText></small></aside>
      <div className="feedStream">{loading?<p className="feedLoading"><SiteText contentKey="CommunityFeed.5dcced8e5ccd">{"Gathering community stories…"}</SiteText></p>:visible.map((post,index)=><article className={`feedPost${post.featured?" featured":""}`} key={post.id} style={{"--post-depth":`${index%3}`}}>
        <div className="feedPostImage" style={{backgroundImage:`linear-gradient(180deg,rgba(9,34,47,.04),rgba(9,34,47,.72)),url(${post.image_url||'/images/banner.png'})`}}><button type="button" className="feedImageEnlarge" aria-label={`Enlarge image for ${post.title}`} aria-haspopup="dialog" onClick={()=>setEnlargedPost(post)}><span><SiteText contentKey="CommunityFeed.ccd3e4d5630f">{"Enlarge image ↗"}</SiteText></span></button><span>{post.category}</span>{post.featured&&<b><SiteText contentKey="CommunityFeed.bd3f4946eded">{"Editor’s pick"}</SiteText></b>}<div><small>{formatDate(post.created_at)}</small><strong>{post.title}</strong></div></div>
        <div className="feedPostBody"><div className="feedAuthor">{user?.role==="admin"&&<button type="button" className="secondaryButton" disabled={publishing} onClick={()=>editPost(post)} aria-label={`Edit post: ${post.title}`}><SiteText contentKey="CommunityFeed.a1933147e7c8">{"Edit post"}</SiteText></button>}<span>{post.avatar_url?<img src={post.avatar_url} alt=""/>:<>{post.first_name[0]}{post.last_name[0]}</>}</span><p><strong>{post.first_name} {post.last_name}</strong><small><SiteText contentKey="CommunityFeed.c43ba5cda282">{"Impact Arlington editorial team"}</SiteText></small></p></div><p className="feedCopy"><LinkedText>{post.body}</LinkedText></p><div className="feedStats"><span>{post.like_count}<SiteText contentKey="CommunityFeed.7ed7ef1e63ee">{" likes"}</SiteText></span><span>{post.comments.length}<SiteText contentKey="CommunityFeed.28037aeb4e2c">{" comments"}</SiteText></span><span>{post.share_count}<SiteText contentKey="CommunityFeed.11a807f1f8b0">{" shares"}</SiteText></span></div><div className="feedActions"><button className={post.liked?"active":""} onClick={()=>action(post,"like")}><SiteText section="CommunityFeed">{post.liked?"♥ Liked":"♡ Like"}</SiteText></button><button onClick={()=>setOpenComments(openComments===post.id?null:post.id)}><SiteText contentKey="CommunityFeed.64545279e9eb">{"◯ Comment"}</SiteText></button><button onClick={()=>action(post,"share")}><SiteText contentKey="CommunityFeed.c2940aeb3f1f">{"↗ Share"}</SiteText></button></div>
        {openComments===post.id&&<div className="feedComments">{post.comments.map(comment=><div key={comment.id}><span>{comment.avatar_url?<img src={comment.avatar_url} alt=""/>:<>{comment.first_name[0]}{comment.last_name[0]}</>}</span><p><strong>{comment.first_name} {comment.last_name}</strong>{comment.body}</p></div>)}{!post.comments.length&&<p className="feedEmptyComments"><SiteText contentKey="CommunityFeed.f5acb1705efc">{"Start a positive conversation."}</SiteText></p>}<form onSubmit={event=>submitComment(event,post)}><input required maxLength="500" placeholder={user?"Write a comment…":"Sign in to comment"} value={comments[post.id]||""} onChange={event=>setComments({...comments,[post.id]:event.target.value})}/><button><SiteText contentKey="CommunityFeed.a5554622c655">{"Post"}</SiteText></button></form></div>}
        </div>
      </article>)}{!loading&&!visible.length&&<div className="feedEmpty"><span>◇</span><h3><SiteText contentKey="CommunityFeed.9ff1a37f0f1d">{"No posts in this category yet"}</SiteText></h3><p><SiteText contentKey="CommunityFeed.8eb87f0e7cad">{"The Impact Arlington team will publish something here soon."}</SiteText></p></div>}</div>
    </div>
    {enlargedPost&&<ImageLightbox src={enlargedPost.image_url||"/images/banner.png"} title={enlargedPost.title} onClose={()=>setEnlargedPost(null)}/>}
  </section>;
}

export default CommunityFeed;
